// Region registry + loader. The heavy geometry lives in data/maps/<id>.json
// (generated by tools/build-maps.mjs, checked in); this module only knows the
// menu metadata and caches loads.

export const REGIONS = [
  { id: 'europe', label: 'Europe', kind: 'countries' },
  { id: 'africa', label: 'Africa', kind: 'countries' },
  { id: 'se-asia', label: 'South East Asia', kind: 'countries' },
  { id: 'w-asia', label: 'Western Asia', kind: 'countries' },
  { id: 'oceania', label: 'Australasia & Polynesia', kind: 'countries' },
  { id: 'c-america', label: 'Central America', kind: 'countries' },
  { id: 's-america', label: 'South America', kind: 'countries' },
  { id: 'n-america', label: 'North America & Caribbean', kind: 'countries' },
  { id: 'usa', label: 'USA', kind: 'states' },
  { id: 'england', label: 'England', kind: 'states' },
  { id: 'scotland', label: 'Scotland', kind: 'states' },
  { id: 'wales', label: 'Wales', kind: 'states' },
  { id: 'northern-ireland', label: 'Northern Ireland', kind: 'states' },
  { id: 'ireland', label: 'Ireland', kind: 'states' },
  { id: 'canada', label: 'Canada', kind: 'states' },
  { id: 'brazil', label: 'Brazil', kind: 'states' },
  { id: 'australia', label: 'Australia', kind: 'states' },
  { id: 'japan', label: 'Japan', kind: 'states' },
];

export function regionMeta(id) { return REGIONS.find((r) => r.id === id) || null; }

const cache = new Map();
export async function loadRegion(id) {
  if (!regionMeta(id)) throw new Error(`Unknown region ${id}`);
  if (!cache.has(id)) {
    cache.set(id, fetch(new URL(`../data/maps/${id}.json`, import.meta.url))
      .then((r) => { if (!r.ok) throw new Error(`Could not load map (${r.status})`); return r.json(); })
      .catch((e) => { cache.delete(id); throw e; }));
  }
  return cache.get(id);
}
