// All legal two-letter words from tournament word lists.
//
// NWL: NASPA Word List 2023 (North America) — 107 words.
// Collins: Collins Word List 2021 (international) — those 107 plus
// the 20 words flagged `collinsOnly` below, 127 total.
// Source: github.com/scrabblewords/scrabblewords (tournament word lists).

export const TWO_LETTER_WORDS = [
  { w: 'AA', d: 'rough, cindery lava' },
  { w: 'AB', d: 'an abdominal muscle' },
  { w: 'AD', d: 'an advertisement' },
  { w: 'AE', d: 'one' },
  { w: 'AG', d: 'agriculture' },
  { w: 'AH', d: 'to exclaim in surprise (aah)' },
  { w: 'AI', d: 'a three-toed sloth' },
  { w: 'AL', d: 'an East Indian tree' },
  { w: 'AM', d: 'form of the verb "be"' },
  { w: 'AN', d: 'used before a vowel sound' },
  { w: 'AR', d: 'the letter R' },
  { w: 'AS', d: 'to the same degree' },
  { w: 'AT', d: 'to respond to someone online' },
  { w: 'AW', d: 'expressing protest or disgust' },
  { w: 'AX', d: 'to cut with an axe' },
  { w: 'AY', d: 'aye; an affirmative vote' },
  { w: 'BA', d: 'the eternal soul (Egyptian myth)' },
  { w: 'BE', d: 'to have actuality' },
  { w: 'BI', d: 'a bisexual person' },
  { w: 'BO', d: 'a pal' },
  { w: 'BY', d: 'a pass in certain card games' },
  { w: 'CH', d: 'dialect form of I', collinsOnly: true },
  { w: 'DA', d: 'dad' },
  { w: 'DE', d: 'of; from' },
  { w: 'DI', d: 'plural of deus (god)', collinsOnly: true },
  { w: 'DO', d: 'first tone of the musical scale; to perform' },
  { w: 'EA', d: 'a river (dialect)', collinsOnly: true },
  { w: 'ED', d: 'education' },
  { w: 'EE', d: 'an eye (Scots)', collinsOnly: true },
  { w: 'EF', d: 'the letter F' },
  { w: 'EH', d: 'expressing doubt or surprise' },
  { w: 'EL', d: 'an elevated railroad' },
  { w: 'EM', d: 'a typographic unit' },
  { w: 'EN', d: 'half of an em' },
  { w: 'ER', d: 'expressing hesitation' },
  { w: 'ES', d: 'the letter S (ess)' },
  { w: 'ET', d: 'past tense of eat' },
  { w: 'EW', d: 'expressing disgust' },
  { w: 'EX', d: 'to cross out' },
  { w: 'FA', d: 'fourth tone of the musical scale' },
  { w: 'FE', d: 'a Hebrew letter' },
  { w: 'FY', d: 'expressing disapproval (fie)', collinsOnly: true },
  { w: 'GI', d: 'a martial arts garment' },
  { w: 'GO', d: 'a Japanese board game; to move along' },
  { w: 'GU', d: 'an old Shetland viol', collinsOnly: true },
  { w: 'HA', d: 'a sound of surprise' },
  { w: 'HE', d: 'a male person' },
  { w: 'HI', d: 'used as a greeting' },
  { w: 'HM', d: 'expressing thoughtful consideration' },
  { w: 'HO', d: 'an exclamation of surprise' },
  { w: 'ID', d: 'a part of the psyche' },
  { w: 'IF', d: 'a possibility' },
  { w: 'IN', d: 'to harvest' },
  { w: 'IO', d: 'a cry of joy', collinsOnly: true },
  { w: 'IS', d: 'form of the verb "be"' },
  { w: 'IT', d: 'third person singular neuter pronoun' },
  { w: 'JA', d: 'yes (German)', collinsOnly: true },
  { w: 'JO', d: 'a sweetheart' },
  { w: 'KA', d: 'the spiritual self (Egyptian religion)' },
  { w: 'KI', d: 'the vital life force (qi)' },
  { w: 'KO', d: 'a Maori digging-stick', collinsOnly: true },
  { w: 'KY', d: 'cattle', collinsOnly: true },
  { w: 'LA', d: 'sixth tone of the musical scale' },
  { w: 'LI', d: 'a Chinese unit of distance' },
  { w: 'LO', d: 'used to attract attention' },
  { w: 'MA', d: 'mother' },
  { w: 'ME', d: 'the self; an ego' },
  { w: 'MI', d: 'third tone of the musical scale' },
  { w: 'MM', d: 'expressing assent or satisfaction' },
  { w: 'MO', d: 'a moment' },
  { w: 'MU', d: 'a Greek letter' },
  { w: 'MY', d: 'possessive form of I' },
  { w: 'NA', d: 'no; not' },
  { w: 'NE', d: 'born with the name of' },
  { w: 'NO', d: 'a negative reply' },
  { w: 'NU', d: 'a Greek letter' },
  { w: 'NY', d: 'to approach (nigh)', collinsOnly: true },
  { w: 'OB', d: 'an objection', collinsOnly: true },
  { w: 'OD', d: 'a hypothetical natural force' },
  { w: 'OE', d: 'a whirlwind off the Faeroe Islands' },
  { w: 'OF', d: 'coming from' },
  { w: 'OH', d: 'to exclaim in surprise' },
  { w: 'OI', d: 'expressing dismay (oy)' },
  { w: 'OK', d: 'okay' },
  { w: 'OM', d: 'a mantra used in contemplation' },
  { w: 'ON', d: 'the batsman’s side in cricket' },
  { w: 'OO', d: 'wool (Scots)', collinsOnly: true },
  { w: 'OP', d: 'a style of abstract art' },
  { w: 'OR', d: 'the heraldic color gold' },
  { w: 'OS', d: 'a bone; an orifice; an esker' },
  { w: 'OU', d: 'a man, a bloke (South African)', collinsOnly: true },
  { w: 'OW', d: 'expressing sudden pain' },
  { w: 'OX', d: 'a hoofed mammal; a clumsy person' },
  { w: 'OY', d: 'expressing dismay or pain' },
  { w: 'PA', d: 'a father' },
  { w: 'PE', d: 'a Hebrew letter' },
  { w: 'PI', d: 'a Greek letter; to jumble' },
  { w: 'PO', d: 'a chamber pot' },
  { w: 'QI', d: 'the vital life force (Chinese thought)' },
  { w: 'RE', d: 'second tone of the musical scale' },
  { w: 'SH', d: 'used to urge silence' },
  { w: 'SI', d: 'seventh tone of the musical scale (ti)' },
  { w: 'SO', d: 'fifth tone of the musical scale (sol)' },
  { w: 'ST', d: 'hush', collinsOnly: true },
  { w: 'TA', d: 'an expression of gratitude' },
  { w: 'TE', d: 'seventh tone of the musical scale (ti)' },
  { w: 'TI', d: 'seventh tone of the musical scale' },
  { w: 'TO', d: 'in the direction of' },
  { w: 'UG', d: 'to arouse loathing in', collinsOnly: true },
  { w: 'UH', d: 'expressing hesitation' },
  { w: 'UM', d: 'to pause in speaking' },
  { w: 'UN', d: 'one' },
  { w: 'UP', d: 'to raise' },
  { w: 'UR', d: 'expressing hesitation', collinsOnly: true },
  { w: 'US', d: 'objective case of we' },
  { w: 'UT', d: 'the musical tone C (French solmization)' },
  { w: 'WE', d: 'first person plural pronoun' },
  { w: 'WO', d: 'woe' },
  { w: 'XI', d: 'a Greek letter' },
  { w: 'XU', d: 'a monetary unit of Vietnam' },
  { w: 'YA', d: 'an Asian pear' },
  { w: 'YE', d: 'you' },
  { w: 'YO', d: 'used to call attention' },
  { w: 'YU', d: 'a precious jade (Chinese)', collinsOnly: true },
  { w: 'ZA', d: 'a pizza' },
  { w: 'ZE', d: 'gender-neutral singular pronoun', collinsOnly: true },
  { w: 'ZO', d: 'a yak-cow crossbreed', collinsOnly: true },
];
