// Element data loader — one JSON with sets + per-element name/sym/num/mass/
// grid position/family/phase (generated by tools/build-data.mjs, checked in).

let cache = null;

export async function loadData() {
  if (!cache) {
    cache = fetch(new URL('../data/elements.json', import.meta.url))
      .then((r) => { if (!r.ok) throw new Error(`Could not load element data (${r.status})`); return r.json(); })
      .catch((e) => { cache = null; throw e; });
  }
  return cache;
}

export function setMetaOf(data, id) {
  return data.sets.find((s) => s.id === id) || null;
}

export function setEls(data, id) {
  const s = setMetaOf(data, id);
  return s ? s.els.split(' ') : [];
}

// Atomic mass for display: "55.85 u" — full stored precision is overkill in
// the UI (the reveal uses a collision-aware formatter in modes.js instead).
export function fmtMass(m) {
  return `${m >= 100 ? m.toFixed(1) : m.toFixed(2)} u`;
}
