// Country data loader — one JSON with regions + per-country name/alt/pop/area
// (generated by tools/build-data.mjs, checked in). Flags live in data/flags/.

let cache = null;

export async function loadData() {
  if (!cache) {
    cache = fetch(new URL('../data/countries.json', import.meta.url))
      .then((r) => { if (!r.ok) throw new Error(`Could not load country data (${r.status})`); return r.json(); })
      .catch((e) => { cache = null; throw e; });
  }
  return cache;
}

export function flagUrl(iso) {
  return new URL(`../data/flags/${iso.toLowerCase()}.svg`, import.meta.url).href;
}

export function regionMetaOf(data, id) {
  return data.regions.find((r) => r.id === id) || null;
}

export function regionIso(data, id) {
  const r = regionMetaOf(data, id);
  return r ? r.iso.split(' ') : [];
}

// Compact number for the reveal lines: 1.4B, 67.5M, 825.
export function fmtBig(n) {
  if (n >= 1e9) return `${(n / 1e9).toFixed(n >= 1e10 ? 0 : 1)}B`;
  if (n >= 1e6) return `${(n / 1e6).toFixed(n >= 1e7 ? 0 : 1)}M`;
  if (n >= 1e3) return `${(n / 1e3).toFixed(n >= 1e4 ? 0 : 1)}k`;
  return String(n);
}
